[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
	"forge-std/=lib/forge-std/src/",
	"openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
	"v3-core/=lib/v3-core/",
	"v3-periphery/=lib/v3-periphery/",
	"v4-core/=lib/v4-core/",
	"v4-periphery/=lib/v4-periphery/",
	"@uniswap/v3-core/=lib/v3-core/",
	"@uniswap/v3-periphery/=lib/v3-periphery/",
	"@sushiswap/sushi-v3-core/=lib/sushi-v3-core/",
	"@sushiswap/sushi-v3-periphery/=lib/sushi-v3-periphery/",
]
viaIR = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
